name: "Synthetic test workflow"

on:
  workflow_dispatch:

jobs:
  Synthetic test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say Hello Step
        id: say_hello
        uses: deferdie/acumen-github-action/.github/actions/Sythetic@main
        with:
          SYNTHETIC_TEST_URL: "https://google.com"