name: "Synthetic test workflow"

on:
  workflow_dispatch:

jobs:
  Synthetic:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test synthetic action
        id: synthetic_test_step
        uses: deferdie/acumen-github-action/.github/actions/Synthetic@master
        with:
          SYNTHETIC_TEST_URL: "https://app.acumenlogs.com/run/watcher/1b5b8642-3d45-4022-9f9b-9a22b3930502"